const markdown = new Map();

markdown.set(
    "1",
    "## Linear Equations\nA linear equation is an equation that can be written in the form `ax + b = 0`, where a and b are constants and x is a variable.\n\nLinear equations are important in mathematics and other fields because they can be used to model many real-world situations and problems. For example, a linear equation can be used to model the relationship between the amount of money you earn and the number of hours you work, or the relationship between the distance you travel and the time it takes.\n\nSolving a linear equation means finding the value of x that makes the equation true. This can be done by using algebraic techniques, such as manipulating the equation to isolate the variable or using the idea of inverse operations.\n\nHere is an example of a linear equation and its solution:\n```\n3x + 4 = 10n\nx = 6\nx = 2\n```\nIn this example, we start with the equation `3x + 4 = 10` We use the inverse operation of addition (subtraction) to isolate the variable x on one side of the equation, and then we use the inverse operation of multiplication (division) to find the value of x that makes the equation true. The final step is to check our solution to make sure it works:\n```\n3x + 4 = 10\n3 * 2 + 4 = 10\n6 + 4 = 10\n10 = 10\n```\n\nAs you can see, when x is equal to 2, the equation is true. This means that 2 is the solution to the linear equation."
);

export const loremIpsum = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum nunc aliquet bibendum enim facilisis. Pretium quam vulputate dignissim suspendisse in est ante in. Sagittis id consectetur purus ut. Mi proin sed libero enim sed faucibus turpis in eu. Mattis nunc sed blandit libero volutpat. Purus ut faucibus pulvinar elementum integer. Consequat id porta nibh venenatis cras. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Fermentum odio eu feugiat pretium nibh. Non nisi est sit amet facilisis magna etiam tempor orci. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Sapien et ligula ullamcorper malesuada proin libero. Mauris pellentesque pulvinar pellentesque habitant morbi. In est ante in nibh mauris cursus mattis. Faucibus et molestie ac feugiat. Aliquam purus sit amet luctus. Praesent tristique magna sit amet purus gravida quis blandit.

Sit amet consectetur adipiscing elit ut aliquam purus. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Integer eget aliquet nibh praesent tristique magna. Pellentesque elit ullamcorper dignissim cras tincidunt. Ut eu sem integer vitae justo eget magna. Sagittis eu volutpat odio facilisis. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Urna nec tincidunt praesent semper. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Volutpat commodo sed egestas egestas. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Adipiscing enim eu turpis egestas pretium aenean pharetra. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Egestas dui id ornare arcu odio. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Eu mi bibendum neque egestas congue. At augue eget arcu dictum.

Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Nibh sed pulvinar proin gravida hendrerit. Elementum eu facilisis sed odio morbi quis commodo. Commodo viverra maecenas accumsan lacus vel. Et leo duis ut diam quam nulla porttitor massa. Arcu risus quis varius quam quisque id. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Vel risus commodo viverra maecenas accumsan. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Nibh cras pulvinar mattis nunc sed. Ut diam quam nulla porttitor. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Posuere sollicitudin aliquam ultrices sagittis orci a. A iaculis at erat pellentesque adipiscing commodo elit. Sed turpis tincidunt id aliquet risus. Egestas maecenas pharetra convallis posuere morbi leo urna. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus.

Tincidunt dui ut ornare lectus sit amet est placerat. Integer eget aliquet nibh praesent tristique magna sit amet. Vitae purus faucibus ornare suspendisse sed nisi. Vitae tortor condimentum lacinia quis vel eros. Est pellentesque elit ullamcorper dignissim cras tincidunt. Libero id faucibus nisl tincidunt. Nam aliquam sem et tortor consequat id porta nibh venenatis. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Integer feugiat scelerisque varius morbi. Est ante in nibh mauris cursus mattis molestie. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. In hac habitasse platea dictumst. Dignissim enim sit amet venenatis urna cursus.

Bibendum ut tristique et egestas. Commodo nulla facilisi nullam vehicula ipsum a. Magna sit amet purus gravida quis blandit turpis. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Sit amet dictum sit amet. Egestas sed tempus urna et pharetra. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Risus nullam eget felis eget nunc. Tincidunt lobortis feugiat vivamus at augue eget. Nulla pellentesque dignissim enim sit amet venenatis urna.

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum nunc aliquet bibendum enim facilisis. Pretium quam vulputate dignissim suspendisse in est ante in. Sagittis id consectetur purus ut. Mi proin sed libero enim sed faucibus turpis in eu. Mattis nunc sed blandit libero volutpat. Purus ut faucibus pulvinar elementum integer. Consequat id porta nibh venenatis cras. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Fermentum odio eu feugiat pretium nibh. Non nisi est sit amet facilisis magna etiam tempor orci. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Sapien et ligula ullamcorper malesuada proin libero. Mauris pellentesque pulvinar pellentesque habitant morbi. In est ante in nibh mauris cursus mattis. Faucibus et molestie ac feugiat. Aliquam purus sit amet luctus. Praesent tristique magna sit amet purus gravida quis blandit.

Sit amet consectetur adipiscing elit ut aliquam purus. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Integer eget aliquet nibh praesent tristique magna. Pellentesque elit ullamcorper dignissim cras tincidunt. Ut eu sem integer vitae justo eget magna. Sagittis eu volutpat odio facilisis. Faucibus ornare suspendisse sed nisi lacus sed viverra tellus in. Urna nec tincidunt praesent semper. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Volutpat commodo sed egestas egestas. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Adipiscing enim eu turpis egestas pretium aenean pharetra. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Egestas dui id ornare arcu odio. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Eu mi bibendum neque egestas congue. At augue eget arcu dictum.

Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Nibh sed pulvinar proin gravida hendrerit. Elementum eu facilisis sed odio morbi quis commodo. Commodo viverra maecenas accumsan lacus vel. Et leo duis ut diam quam nulla porttitor massa. Arcu risus quis varius quam quisque id. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Vel risus commodo viverra maecenas accumsan. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Nibh cras pulvinar mattis nunc sed. Ut diam quam nulla porttitor. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Posuere sollicitudin aliquam ultrices sagittis orci a. A iaculis at erat pellentesque adipiscing commodo elit. Sed turpis tincidunt id aliquet risus. Egestas maecenas pharetra convallis posuere morbi leo urna. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus.

Tincidunt dui ut ornare lectus sit amet est placerat. Integer eget aliquet nibh praesent tristique magna sit amet. Vitae purus faucibus ornare suspendisse sed nisi. Vitae tortor condimentum lacinia quis vel eros. Est pellentesque elit ullamcorper dignissim cras tincidunt. Libero id faucibus nisl tincidunt. Nam aliquam sem et tortor consequat id porta nibh venenatis. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Integer feugiat scelerisque varius morbi. Est ante in nibh mauris cursus mattis molestie. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. In hac habitasse platea dictumst. Dignissim enim sit amet venenatis urna cursus.

Bibendum ut tristique et egestas. Commodo nulla facilisi nullam vehicula ipsum a. Magna sit amet purus gravida quis blandit turpis. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Sit amet dictum sit amet. Egestas sed tempus urna et pharetra. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Risus nullam eget felis eget nunc. Tincidunt lobortis feugiat vivamus at augue eget. Nulla pellentesque dignissim enim sit amet venenatis urna.
`;

export default markdown;
